### PR TITLE
scipy: fix libblas warning

### PR DESCRIPTION
**Pull request by lucascolley**
closes gh-3 based on the guidance in https://github.com/prefix-dev/pixi/pull/1786

### CODE REVIEW

**Comment by rgommers** [comment]
That seems to work nicely now, thanks Lucas!

Default env:
```
% pixi ls --platform linux-64 | rg "blas|mkl"
blas-devel                            3.9.0        23_linux64_openblas  14.5 KiB   conda  blas-devel-3.9.0-23_linux64_openblas.conda
libblas                               3.9.0        23_linux64_openblas  14.5 KiB   conda  libblas-3.9.0-23_linux64_openblas.conda
libcblas                              3.9.0        23_linux64_openblas  14.5 KiB   conda  libcblas-3.9.0-23_linux64_openblas.conda
liblapack                             3.9.0        23_linux64_openblas  14.5 KiB   conda  liblapack-3.9.0-23_linux64_openblas.conda
liblapacke                            3.9.0        23_linux64_openblas  14.5 KiB   conda  liblapacke-3.9.0-23_linux64_openblas.conda
libopenblas                           0.3.27       pthreads_hac2b453_1  5.3 MiB    conda  libopenblas-0.3.27-pthreads_hac2b453_1.conda
openblas                              0.3.27       pthreads_h9eca1d5_1  5.5 MiB    conda  openblas-0.3.27-pthreads_h9eca1d5_1.conda
```

`mkl` env:
```
% pixi ls -e mkl --platform linux-64 | rg "blas|mkl"
Environment: mkl
blas-devel                            3.9.0        23_linux64_mkl         14.3 KiB   conda  blas-devel-3.9.0-23_linux64_mkl.conda
libblas                               3.9.0        23_linux64_mkl         14.9 KiB   conda  libblas-3.9.0-23_linux64_mkl.conda
libcblas                              3.9.0        23_linux64_mkl         14.4 KiB   conda  libcblas-3.9.0-23_linux64_mkl.conda
liblapack                             3.9.0        23_linux64_mkl         14.5 KiB   conda  liblapack-3.9.0-23_linux64_mkl.conda
liblapacke                            3.9.0        23_linux64_mkl         14.4 KiB   conda  liblapacke-3.9.0-23_linux64_mkl.conda
mkl                                   2024.1.0     ha957f24_693           121.2 MiB  conda  mkl-2024.1.0-ha957f24_693.conda
mkl-devel                             2024.1.0     ha770c72_693           34.3 KiB   conda  mkl-devel-2024.1.0-ha770c72_693.conda
mkl-include                           2024.1.0     ha957f24_693           679.6 KiB  conda  mkl-include-2024.1.0-ha957f24_693.conda
```

`array-api` env (expecting `mkl` because of `pytorch`):
```
% pixi ls -e array-api --platform linux-64 | rg "blas|mkl"
Environment: array-api
blas-devel                            3.9.0        20_linux64_mkl             13.9 KiB   conda  blas-devel-3.9.0-20_linux64_mkl.conda
libblas                               3.9.0        20_linux64_mkl             14.6 KiB   conda  libblas-3.9.0-20_linux64_mkl.conda
libcblas                              3.9.0        20_linux64_mkl             14.1 KiB   conda  libcblas-3.9.0-20_linux64_mkl.conda
liblapack                             3.9.0        20_linux64_mkl             14.1 KiB   conda  liblapack-3.9.0-20_linux64_mkl.conda
liblapacke                            3.9.0        20_linux64_mkl             14.1 KiB   conda  liblapacke-3.9.0-20_linux64_mkl.conda
libtorch                              2.3.1        cpu_mkl_h0bb0d08_100       47.5 MiB   conda  libtorch-2.3.1-cpu_mkl_h0bb0d08_100.conda
mkl                                   2023.2.0     h84fe81f_50496             156.8 MiB  conda  mkl-2023.2.0-h84fe81f_50496.conda
mkl-devel                             2023.2.0     ha770c72_50496             29 KiB     conda  mkl-devel-2023.2.0-ha770c72_50496.conda
mkl-include                           2023.2.0     h84fe81f_50496             688.1 KiB  conda  mkl-include-2023.2.0-h84fe81f_50496.conda
pytorch                               2.3.1        cpu_mkl_py312h3b258cc_100  23.3 MiB   conda  pytorch-2.3.1-cpu_mkl_py312h3b258cc_100.conda
```

`jax` env (expecting `openblas`):
```
% pixi ls -e jax --platform linux-64 | rg "blas|mkl"
Environment: jax
blas-devel                            3.9.0        23_linux64_openblas  14.5 KiB   conda  blas-devel-3.9.0-23_linux64_openblas.conda
libblas                               3.9.0        23_linux64_openblas  14.5 KiB   conda  libblas-3.9.0-23_linux64_openblas.conda
libcblas                              3.9.0        23_linux64_openblas  14.5 KiB   conda  libcblas-3.9.0-23_linux64_openblas.conda
liblapack                             3.9.0        23_linux64_openblas  14.5 KiB   conda  liblapack-3.9.0-23_linux64_openblas.conda
liblapacke                            3.9.0        23_linux64_openblas  14.5 KiB   conda  liblapacke-3.9.0-23_linux64_openblas.conda
libopenblas                           0.3.27       pthreads_hac2b453_1  5.3 MiB    conda  libopenblas-0.3.27-pthreads_hac2b453_1.conda
openblas                              0.3.27       pthreads_h9eca1d5_1  5.5 MiB    conda  openblas-0.3.27-pthreads_h9eca1d5_1.conda
```

**Review by rgommers — APPROVED** [review]
Rebased and added the lock file changes to match - in it goes.

**Comment by rgommers** [comment]
This really is quite a pleasant tool, isn't it:)

**Comment by lucascolley** [comment]
yes!!

**Pull request merged**
