### PR TITLE
scipy: updates for torch-cuda

### PR DESCRIPTION
**Pull request by lucascolley**
@traversaro @ruben-arts IIUC, from the discussion on discord, we want to do this to help pick up the correct `pytorch` builds when we have both `cuda` and `torch` features here?

### CODE REVIEW

**Comment by traversaro** [comment]
> @traversaro @ruben-arts IIUC, from the discussion on discord, we want to do this to help pick up the correct `pytorch` builds when we have both `cuda` and `torch` features here?

Unfortunately this will just ensure that if cuda is installed, a version in the 12.* series will be installed. If everything works in PyTorch packaging, if the `__cuda` virtual package is present, the pytorch with cuda support will be installed, but that is just a byproduct of the cuda builds of pytorch having an higher build number, it is not enforced in any way in your pixi metadata. For example, if at some point a pytorch cuda build will get marked as broken, pixi will start installing the newest pytorch version, even if is compiled just with cpu support. I know that it is ugly, but as far as I know the only way to ensure that a cuda PyTorch build is used is to add a constraint on the build string, a bit like you did with jaxlib.

**Comment by rgommers** [comment]
We should start using `pytorch-cpu` and `pytorch-gpu` dependencies for `feature.torch-cpu|gpu`, just like we split JAX dependencies.

**Comment by rgommers** [comment]
The change here is fine though - we want only CUDA 12 at this point.

**Comment by traversaro** [comment]
>  I know that it is ugly, but as far as I know the only way to ensure that a cuda PyTorch build is used is to add a constraint on the build string, a bit like you did with jaxlib.

Sorry, this is wrong: in the pytorch case you can also on install pytorch-gpu package to achieve the same.

**Review by rgommers — APPROVED** [review]
Merged now, thanks @lucascolley! And thanks @traversaro for the help!

**Pull request closed without merging**
